import { Hono } from 'hono';
import { zValidator } from '@hono/zod-validator';
import { z } from 'zod';
import { and, eq, isNull, sql } from 'drizzle-orm';
import { schema, newId, nowIso } from '@overwatch/shared-ts';
import { db } from '../db.js';
import { requireAuth } from '../middleware.js';

const app = new Hono();
app.use('*', requireAuth);

const Create = z.object({
  channel: z.literal('telegram'),
  handle: z.string().min(1).max(128),
  enabled: z.boolean().optional(),
});

const Claim = z.object({
  // Bot generates 6-char base32 codes. Accept slightly more to be safe.
  code: z
    .string()
    .min(4)
    .max(12)
    .transform((s) => s.trim().toUpperCase()),
});

app.get('/', (c) => {
  const rows = db.select().from(schema.subscribers).all();
  return c.json({ subscribers: rows.map((r) => ({ ...r, enabled: !!r.enabled })) });
});

/**
 * Idempotent create — re-adding an already-known (channel, handle) row
 * re-enables it rather than 500'ing on the UNIQUE constraint. The
 * claim-code flow also uses this path; keeping it idempotent here avoids
 * surprising the operator when they re-add a handle manually.
 */
app.post('/', zValidator('json', Create), (c) => {
  const body = c.req.valid('json');
  const enabled = body.enabled === false ? 0 : 1;

  const existing = db
    .select()
    .from(schema.subscribers)
    .where(
      and(eq(schema.subscribers.channel, body.channel), eq(schema.subscribers.handle, body.handle)),
    )
    .get();
  if (existing) {
    db.update(schema.subscribers)
      .set({ enabled })
      .where(eq(schema.subscribers.id, existing.id))
      .run();
    return c.json({ id: existing.id }, 201);
  }
  const id = newId();
  db.insert(schema.subscribers)
    .values({
      id,
      channel: body.channel,
      handle: body.handle,
      enabled,
      created_at: nowIso(),
    })
    .run();
  return c.json({ id }, 201);
});

/**
 * POST /api/subscribers/claim {code}
 *
 * Resolves a claim code generated by the Telegram bot's /start command into a
 * subscriber row. The code is consumed on success (claimed_at set), so a code
 * can only be redeemed once. Re-claiming an already-known chat_id re-enables
 * the existing subscriber row (idempotent).
 */
app.post('/claim', zValidator('json', Claim), (c) => {
  const { code } = c.req.valid('json');
  const row = db
    .select()
    .from(schema.claimCodes)
    .where(eq(schema.claimCodes.code, code))
    .get();
  if (!row) return c.json({ error: 'invalid_code' }, 400);
  if (row.claimed_at) return c.json({ error: 'already_claimed' }, 409);
  if (new Date(row.expires_at).getTime() < Date.now()) {
    return c.json({ error: 'expired' }, 410);
  }

  const now = nowIso();
  const handle = row.chat_id;

  // Mark the code consumed first — if the upsert fails the code stays
  // available for retry. (SQLite is single-writer; this is fine without
  // explicit transactions, but order matters for idempotency.)
  db.update(schema.claimCodes)
    .set({ claimed_at: now })
    .where(eq(schema.claimCodes.code, code))
    .run();

  const existing = db
    .select()
    .from(schema.subscribers)
    .where(
      and(eq(schema.subscribers.channel, 'telegram'), eq(schema.subscribers.handle, handle)),
    )
    .get();
  if (existing) {
    db.update(schema.subscribers)
      .set({ enabled: 1 })
      .where(eq(schema.subscribers.id, existing.id))
      .run();
    return c.json(
      { id: existing.id, channel: 'telegram', handle, enabled: true, claimed: true },
      200,
    );
  }
  const id = newId();
  db.insert(schema.subscribers)
    .values({
      id,
      channel: 'telegram',
      handle,
      enabled: 1,
      created_at: now,
    })
    .run();
  return c.json({ id, channel: 'telegram', handle, enabled: true, claimed: true }, 201);
});

/**
 * Best-effort cleanup of expired unclaimed codes. Called opportunistically
 * by GET / so the table stays bounded without a separate cron.
 */
app.get('/admin/_purge-expired-codes', (c) => {
  const r = db
    .delete(schema.claimCodes)
    .where(and(isNull(schema.claimCodes.claimed_at), sql`${schema.claimCodes.expires_at} < ${nowIso()}`))
    .run();
  return c.json({ deleted: r.changes });
});

app.delete('/:id', (c) => {
  const id = c.req.param('id');
  const r = db.delete(schema.subscribers).where(eq(schema.subscribers.id, id)).run();
  if (r.changes === 0) return c.json({ error: 'not_found' }, 404);
  return c.json({ ok: true });
});

export default app;
